:title: Lotus
:description: TData Visualisation Tool
:keywords: python, data, students, research, visualisation, plot
:author: Maximilian Anzinger
:revnumber: 0.1.0
:revdate: 2022-04-05
:revremark: 
:showtitle:
:sectnums:
:toc: preamble
:toclevels: 3
:icons: font

= Lotus

Data Visualisation Tool

== About

image:https://img.shields.io/github/release/MaximilianAnzinger/Lotus/StrapDown.js.svg[GitHub release]
image:https://badgen.net/github/last-commit/MaximilianAnzinger/Lotus/Strapdown.js[GitHub last commit]
image:https://img.shields.io/badge/Made%20with-Python-1f425f.svg[python]
image:https://svgshare.com/i/Zhy.svg[linux]
image:https://svgshare.com/i/ZjP.svg[macOS]
image:https://svgshare.com/i/ZhY.svg[windows]
image:https://img.shields.io/badge/maintainer-Maximilian Anzinger-blue[Maintainer]

asdf

== Setup

It is recommendet to download the latest https://github.com/MaximilianAnzinger/Lotus/releases[`Release`]. Extract the files to your prefered working space and continue in section 3.

Furthermore, you can download the repository by either opening a terminal, changing into the desired directory and using git clone `https://github.com/MaximilianAnzinger/Lotus.git` to clone the repository. Note that for this git has to be installed on your system and you might experience more bugs compared to the latest release.

If you don't have git or are unsure on how to use it, then you can scroll to the top, press the green `code` button and download the project as a zip-archive. Note that you first have to unzip the archive before continuing.

== Basic Usage

=== CSV Format

.Your data must be formated as follows:
- First row (`Header`) contains all groups for each `Dataset`. Keep in mind, that the first entry will be omitted.
- The `Header` must be separated from the following `Dataset` by at least one empty row.
- Each `Dataset` starts with the corresponding `Title` followed by a row of the labels.
- Two `Datasets` must be separated by at least one empty row.
- The default delimiter is ','. If you wan't to use another format, please refere to the `Advanced` section.

The following table depicts an example format. You can create a file from scratch or use the provided `example.csv` for guidance.

.Example CSV
|====
| a | Group 1 | Group 2 | ... | Group m  |  |  |
| `At least one empty row` |  |  |  |  |  |  |
| Dataset Title |  |  |  |  |  |  |
| Label 1.1 | ... | Label n.1 | ... | Label 1.m | ... | Label n.m |
| Value 1.1.1 | ... | Value 1.n.1 | ... | Value 1.1.m | ... | Value 1.n.m |
| ... | ... | ... | ... | ... | ... | ... |
| Value k.1.1 | ... | Value k.n.1 | ... | Value k.1.m | ... | Value k.n.m |
| `At least one empty row` |  |  |  |  |  |  |
| Dataset Title |  |  |  |  |  |  |
| Label 1.1 | ... | Label n.1 | ... | Label 1.m | ... | Label n.m |
| Value 1.1.1 | ... | Value 1.n.1 | ... | Value 1.1.m | ... | Value 1.n.m |
| ... | ... | ... | ... | ... | ... | ... |
| Value l.1.1 | ... | Value l.n.1 | ... | Value l.1.m | ... | Value l.n.m |
|====


=== Generating Graphics

asdf

=== Advanced

For more information please refere to the https://github.com/MaximilianAnzinger/Lotus/wiki[`wiki`]

== Contribute

image:https://badgen.net/github/contributors/MaximilianAnzinger/Lotus[Github contributors]

All contributions are appreciated. Feel free to fork the project and create a pull request at any time.

== Additional Notes

asdf

== License
image:https://badgen.net/github/license/MaximilianAnzinger/Lotus/Strapdown.js[GitHub license]

Lotus was created by {author} and is licensed under the https://github.com/MaximilianAnzinger/Lotus/blob/main/LICENSE[MIT License, see `LICENSE`].